language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly

before_install:
  - composer self-update
  - mkdir -p build/logs

install: composer install --prefer-source --dev

before_script:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then PHPUNIT_FLAGS="--coverage-clover ./build/logs/clover.xml"; else PHPUNIT_FLAGS=""; fi

script: phpunit -c tests/travis/travis.phpunit.xml $PHPUNIT_FLAGS

after_script:
  - php vendor/bin/coveralls -v --no-interaction --exclude-no-stmt

matrix:
  allow_failures:
      - php: 7.0
      - php: nightly
